apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: infra
  labels:
    svc: cockroachdb
spec:
  # type: LoadBalancer
  ports:
    - port: 26257
      targetPort: 26257
      protocol: TCP
      name: tcp
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    app: cockroachdb
