version: "3"
services:

  nginx:
    image: nginx:1.15.12
    volumes:
     - ./gunsluo.github.io:/usr/share/nginx/html
     - ./rootfs/defaults/nginx.conf:/etc/nginx/nginx.conf
     - ./rootfs/defaults/blog.template:/etc/nginx/conf.d/blog.template
     - ./certbot/letsencrypt:/etc/letsencrypt
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_HOST=luoji.live
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/blog.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

