apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: infra
spec:
  selector:
    matchLabels:
      app: valkey
  replicas: 1
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.1.3-bookworm
          ports:
            - containerPort: 6379
