apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: infra
  labels:
    svc: valkey
spec:
  # type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp
  selector:
    app: valkey
