apiVersion: v1
kind: Service
metadata:
  name: otel
  namespace: infra
  labels:
    svc: otel
spec:
  # type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: tcp
  selector:
    app: otel
