apiVersion: v1
kind: ConfigMap
metadata:
  name: sysforge-config
  namespace: grassroot
data:
  config.yaml: |
    version: 1.0.0

    serve:
      api:
        base_url: http://sysforge.grassroot.svc.cluster.local:5320/
        port: 5320
        cors:
          enabled: true
          max_age: 12h
          allow_wildcard: true
          allowed_origins:
            - "*"
          allowed_methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - HEAD
            - OPTIONS
          allowed_headers:
            - "*"
            - "Authorization"
          allow_credentials: true
      ui:
        dir: /ui
        lifespan: 144h
      monitor:
        disabled: false
        token: 8dcRptfCssB1fRQUrJhtxZgzelsLvvoXeTvmafCVM6E2Go1svmPW4rvhzyJoE2K4

    auth:
      token:
        issuer: http://127.0.0.1:5556
        lifespan: 24h
        # hs256 hs512
        algorithm: hs256
        key: 01JJG8A9W6H9ZEVRN353N7ZSMK
      credentials:
        - username: super@example.com
          realname: Super
          # bcrypt hash of the string "password"
          password: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          menus:
            - "*"
        - username: admin@example.com
          realname: Admin
          # bcrypt hash of the string "password"
          password: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          menus:
            - ac
        - username: regular@example.com
          realname: Regular
          # bcrypt hash of the string "password"
          password: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          menus:
            - ses
            - sms
      cookies:
        path: "/"
        # strict lax none
        same_site: lax
        domain: ""
        http_only: true

    sessms:
      grpc:
        endpoint: sessmsgrpc.grassroot:6000
        insecure: true
        # maxRetries: 3
        # retryTimeout: 10s
        # ca: ca.crt
        # cert: server.crt
        # key: server.key
        # serverName:

    ac:
      grpc:
        endpoint: acgrpc.grassroot:7001
        insecure: true
        # maxRetries: 3
        # retryTimeout: 10s
        # ca: ca.crt
        # cert: server.crt
        # key: server.key
        # serverName:

    sso:
      grpc:
        endpoint: dex.grassroot:5557
        insecure: true
        # maxRetries: 3
        # retryTimeout: 10s
        # ca: ca.crt
        # cert: server.crt
        # key: server.key
        # serverName:

    dev: false
