version: "3"
services:

  shadowsocks-server:
    image: teddysun/xray:1.8.1
    container_name: xray
    restart: always
    command: >
      /usr/bin/xray -config /etc/xray/config.json
    volumes:
      - ./config:/etc/xray
      - /dev/shm:/dev/shm:rw
    ports:
      - "443:443"
