apiVersion: v1
kind: ConfigMap
metadata:
  name: rm-config
  namespace: grassroot
data:
  config.yaml: |
    version: 1.0.0

    rest:
      # REST_PORT
      port: 6677
      cors:
        # REST_CORS_ENABLED
        enabled: true
        # REST_CORS_MAX_AGE
        max_age: 12h
        # REST_CORS_ALLOWED_ORIGINS
        allowed_origins:
          - '*'
        # REST_CORS_ALLOWED_METHODS="GET POST"
        allowed_methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - HEAD
          - OPTIONS
        # REST_CORS_ALLOWED_HEADERS
        allowed_headers:
          - '*'
          - 'Authorization'
        # REST_CORS_ALLOW_CREDENTIALS
        allow_credentials: true


    admin:
      # unsupported
      administrators:
        - username: admin@example.com
          password: password
      # ADMIN_TOKEN_SECRET
      token_secret: 4d733a750ddfeed4
      # ADMIN_TOKEN_EXPIRED
      token_expired: 2h
      ui:
        # ADMIN_UI_DIR
        dir: /uiadmin
        # ADMIN_UI_ENDPOINT
        endpoint: http://rm.grassroot.svc.cluster.local:6677/v1
        # ADMIN_UI_TIMEOUT
        timeout: 30s
        # ADMIN_UI_COOKIE_EXPIRED
        cookie_expired: 2h


    db:
      # DB_DSN
      dsn: postgres://postgres:password@postgres.infra:5432/resourcemanager?sslmode=disable
      # DB_MAX_IDLE_CONNS
      max_idle_conns: 100
      # DB_MAX_IDLE_CONNS
      max_open_conns: 100
      #conn_max_life_time: 2h
      #conn_max_idle_time: 2h
      #migration_path: migrations/sql

    resource:
      # RESOURCE_NAMESPACE
      namespace: oia
      # RESOURCE_ROOT_PATH
      root_path: /resources

    placeholders:
      - name: sso.logo
        value: https://sso.dev.meeraspace.com/theme/logo.svg
