apiVersion: v1
kind: Service
metadata:
  name: rm
  namespace: grassroot
  labels:
    svc: rm
spec:
  # type: LoadBalancer
  ports:
    - port: 6677
      targetPort: 6677
      protocol: TCP
      name: rm
  selector:
    app: rm
