version: "3"
services:

  shadowsocks-server:
    image: teddysun/xray:1.8.1
    container_name: xray
    restart: always
    volumes:
      - ./config.json:/etc/xray/config.json
      - /dev/shm:/dev/shm:rw
    ports:
      - "443:443"
