apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: infra
  labels:
    type: local
spec:
  storageClassName: local-postgres-storage
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # orbstack is mounted on Mac filesystem /Users/luoji/.orbstack/data/k8s
    path: /Users/luoji/.orbstack/data/k8s/postgres
