apiVersion: apps/v1
kind: Deployment
metadata:
  name: gettoken
  namespace: grassroot
spec:
  selector:
    matchLabels:
      app: gettoken
  replicas: 1
  template:
    metadata:
      labels:
        app: gettoken
    spec:
      containers:
        - name: gettoken
          image: gunsluo/dex-client:latest
          command:
            - /usr/local/bin/dex-client
            - --issuer=http://dex.grassroot.svc.cluster.local:5556
            - --listen=http://0.0.0.0:4444
            - --client-id=example-app
            - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
            - --redirect-uri=http://gettoken.grassroot.svc.cluster.local:4444/callback
          ports:
            - containerPort: 4444
